"""empty message

Revision ID: 9a873710d0a3
Revises: 58672493bd68
Create Date: 2019-02-04 15:26:22.198921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a873710d0a3'
down_revision = '58672493bd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_permissions'), 'roles', ['permissions'], unique=True)
    op.create_index(op.f('ix_roles_role'), 'roles', ['role'], unique=True)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_roles_role'), table_name='roles')
    op.drop_index(op.f('ix_roles_permissions'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
